// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFx254Gl0OsleYOT3ZvdBa3NleYKhCF8M',
    appId: '1:533010108429:web:1c660753bb7905873dc544',
    messagingSenderId: '533010108429',
    projectId: 'hackthon-techtechtechnology',
    authDomain: 'hackthon-techtechtechnology.firebaseapp.com',
    databaseURL: 'https://hackthon-techtechtechnology-default-rtdb.firebaseio.com',
    storageBucket: 'hackthon-techtechtechnology.firebasestorage.app',
    measurementId: 'G-Z82N0MM6LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzro4LMXDwcVujZ4D-46EFBZLUNpePmc4',
    appId: '1:533010108429:android:acd100f8fff2cb083dc544',
    messagingSenderId: '533010108429',
    projectId: 'hackthon-techtechtechnology',
    databaseURL: 'https://hackthon-techtechtechnology-default-rtdb.firebaseio.com',
    storageBucket: 'hackthon-techtechtechnology.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmSiyH88JhmpJinLNktOIID0ddqSSEggI',
    appId: '1:533010108429:ios:198ac8820c59f2f83dc544',
    messagingSenderId: '533010108429',
    projectId: 'hackthon-techtechtechnology',
    databaseURL: 'https://hackthon-techtechtechnology-default-rtdb.firebaseio.com',
    storageBucket: 'hackthon-techtechtechnology.firebasestorage.app',
    iosBundleId: 'com.example.breathChecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmSiyH88JhmpJinLNktOIID0ddqSSEggI',
    appId: '1:533010108429:ios:198ac8820c59f2f83dc544',
    messagingSenderId: '533010108429',
    projectId: 'hackthon-techtechtechnology',
    databaseURL: 'https://hackthon-techtechtechnology-default-rtdb.firebaseio.com',
    storageBucket: 'hackthon-techtechtechnology.firebasestorage.app',
    iosBundleId: 'com.example.breathChecker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFx254Gl0OsleYOT3ZvdBa3NleYKhCF8M',
    appId: '1:533010108429:web:ca9ffddb38c2f8303dc544',
    messagingSenderId: '533010108429',
    projectId: 'hackthon-techtechtechnology',
    authDomain: 'hackthon-techtechtechnology.firebaseapp.com',
    databaseURL: 'https://hackthon-techtechtechnology-default-rtdb.firebaseio.com',
    storageBucket: 'hackthon-techtechtechnology.firebasestorage.app',
    measurementId: 'G-VKXX892CJ0',
  );
}
